# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\kryst\Desktop\Work Projects\ISARP\MasterAPP\ui\NewDomain.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EnterNewDomain(object):
    def setupUi(self, EnterNewDomain):
        EnterNewDomain.setObjectName("EnterNewDomain")
        EnterNewDomain.setWindowModality(QtCore.Qt.ApplicationModal)
        EnterNewDomain.resize(345, 101)
        EnterNewDomain.setMinimumSize(QtCore.QSize(337, 101))
        EnterNewDomain.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(EnterNewDomain)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(EnterNewDomain)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 226, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.d_lineEdit_1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.d_lineEdit_1.setMinimumSize(QtCore.QSize(160, 0))
        self.d_lineEdit_1.setInputMask("")
        self.d_lineEdit_1.setObjectName("d_lineEdit_1")
        self.horizontalLayout_3.addWidget(self.d_lineEdit_1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(3, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.d_lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.d_lineEdit_2.setMaximumSize(QtCore.QSize(41, 16777215))
        self.d_lineEdit_2.setMaxLength(10)
        self.d_lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.d_lineEdit_2.setObjectName("d_lineEdit_2")
        self.horizontalLayout_3.addWidget(self.d_lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.d_lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.d_lineEdit_3.setMinimumSize(QtCore.QSize(50, 0))
        self.d_lineEdit_3.setInputMask("")
        self.d_lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.d_lineEdit_3.setObjectName("d_lineEdit_3")
        self.horizontalLayout_2.addWidget(self.d_lineEdit_3)
        self.d_lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.d_lineEdit_4.setMinimumSize(QtCore.QSize(120, 0))
        self.d_lineEdit_4.setInputMask("")
        self.d_lineEdit_4.setText("")
        self.d_lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.d_lineEdit_4.setObjectName("d_lineEdit_4")
        self.horizontalLayout_2.addWidget(self.d_lineEdit_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addWidget(self.groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(EnterNewDomain)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(EnterNewDomain)
        self.buttonBox.accepted.connect(EnterNewDomain.accept)
        self.buttonBox.rejected.connect(EnterNewDomain.reject)
        QtCore.QMetaObject.connectSlotsByName(EnterNewDomain)

    def retranslateUi(self, EnterNewDomain):
        _translate = QtCore.QCoreApplication.translate
        EnterNewDomain.setWindowTitle(_translate("EnterNewDomain", "Enter New Domain"))
        self.groupBox.setTitle(_translate("EnterNewDomain", "New Domain"))
        self.d_lineEdit_1.setText(_translate("EnterNewDomain", "wakemaster.cz"))
        self.d_lineEdit_1.setPlaceholderText(_translate("EnterNewDomain", "Domain Host or IP Address"))
        self.label_4.setText(_translate("EnterNewDomain", ":"))
        self.d_lineEdit_2.setText(_translate("EnterNewDomain", "10222"))
        self.d_lineEdit_2.setPlaceholderText(_translate("EnterNewDomain", "Port"))
        self.d_lineEdit_3.setPlaceholderText(_translate("EnterNewDomain", "User"))
        self.d_lineEdit_4.setPlaceholderText(_translate("EnterNewDomain", "Password"))
